# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59df83a9754dcb4d06ed4810895990cc99feffdaf5cc53651522ad0ad3dcff413464a348615ad2f5a54383971ee1c91f17455693f3db0a437c6e290e26abc3b2

test:
  secret_key_base: 901029d4855249fb627326cd54e20f8fdeac81aad08b9a4c4099735ddae16322dbb4b09a8ca8ccfe2506f2ac3fecb513b18bff4e10def9cf4fc27739599b2067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
